package main

// List of known port names, taken from here:
// https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Well-known_ports
var knownPortNames2 = map[int] string {
	0: "Reserved",
	1: "TCPMUX",
	5: "Remote Job Entry",
	7: "Echo Protocol",
	9: "Discard Protocol",
	11: "SYSTAT Service",
	13: "Daytime Protocol",
	17: "QOTD (Quote of the Day) Protocol",
	18: "Message Send Protocol",
	19: "Character Generator Protocol",
	20: "File Transfer Protocol (FTP) data transfer",
	21: "File Transfer Protocol (FTP) control (command)",
	22: "Secure Shell (SSH)",
	23: "Telnet Protocol",
	25: "Simple Mail Transfer Protocol (SMTP)",
	37: "Time Protocol",
	38: "Remote Access Protocol (RAP)",
	39: "Resource Location Protocol (RLP)",
	42: "Host Name Server Protocol",
	43: "WHOIS Protocol",
	49: "TACACS Login Host Protocol",
	50: "Remote Mail Checking Protocol",
	52: "Xerox Network Systems (XNS) Time Protocol",
	53: "Domain Name System (DNS)",
	54: "Xerox Network Systems (XNS) clearinghouse",
	56: "Xerox Network Systems (XNS) authentication",
	57: "Any private terminal access",
	58: "Xerox Network Systems (XNS) mail",
	66: "SQL-NET",
	67: "Bootstrap Protocol (BOOTP) Server",
	68: "Bootstrap Protocol (BOOTP) Client",
	69: "Trivial File Transfer Protocol (TFTP)",
	70: "Gopher Protocol",
	71-74: "NETJRS Protocol",
	75: "Any private dial out service",
	77: "Any private Remote job entry",
	79: "Finger Protocol",
	80: "Hyper Text Transfer Protocol (HTTP)",
	81: "TorPark onion routing",
	82: "TorPark control",
	87: "Any private terminal link",
	88: "Kerberos authentication system",
	90: "DNSIX (DoD Network Security for Information Exchange",
	101: "NIC host name",
	102: "ISO Transport Service Access Point (TSAP)",
	104: "Digital Imaging and Communications in Medicine (DISCOM)",
	105: "CCSO Nameserver",
	107: "Remote User Telnet Service (RTelnet)",
	108: "IBM Systems Network Architecture (SNA) gateway access server",
	109: "Post Office Protocol, version 2 (POP2)",
	110: "Post Office Protocol, version 3 (POP3)",
	111: "Open Network Computing Remote Procedure Call (ONC RPC or SunRPC)",
	113: "Authentication Service (auth)",
	115: "Simple File Transfer Protocol (SFTP)",
	117: "UUCP Mapping Project",
	118: "Structured Query Language (SQL) Services",
	119: "Network News Transfer Protocol (NNTP)",
	123: "Network Time Protocol (NTP)",
	135: "Microsoft End Point Mapper (EPMAP)",
	137: "NetBIOS Name Service",
	138: "NetBIOS Datagram Service",
	139: "NetBIOS Session Service",
	143: "Internet MEssage ACcess Protocol (IMAP)",
	152: "Background File Transfer Program (BFTP)",
	153: "Simple Gateway Monitoring Protocol (SGMP)",
	156: "Structured Query Language (SQL) Services",
	158: "Distributed Mail System Protocol (DMSP or PcMail)",
	161: "Simple Network Management Protocol (SNMP)",
	162: "Simple Network Management Protocol Trap (SNMPTRAP)",
	170: "Printer Server",
	177: "X Display Manager Control Protocol (XDMCP)",
	179: "Border Gateway Protocol (BGP)",
	194: "Internet Relay Chat (IRC)",
	199: "SNMP multiplexing protocol (SMUX)",
	201: "AppleTalk Routing Maintenance",
	209: "Quick Mail Transfer Protocol",
	210: "ANSI Z39.50",
	213: "Internetwork Packet Exchange (IPX)",
	218: "Message posting protocol (MPP)",
	220: "Internet Message Access Protocol (IMAP) version 3",
	225-241: "Reserved",
	249-255: "Reserved",
	259: "Efficient Short Remote Operations (ESRO)",
	262: "Arcisdms",
	264: "Border Gateway Multicast Protocol (BGMP)",
	280: "http-mgmt", // RENAME
	308: "Novastor Online Backup",
	311: "Mac OS X Server Admin",
	318: "PKIX Time Stamp Protocol (TSP)",
	319: "Precision Time Protocol (PTP) event messages",
	320: "Precision Time Protocol (PTP) general messages",
	350: "Mapping of Airline Traffic over Internet Protocol (MATIP) type A",
	351: "Mapping of Airline Traffic over Internet Protocol (MATIP) type B",
	356: "cloanto-net-1 (used by Cloanto Amiga Explorer and VMs)", // RENAME
	366: "On-Demand Mail Relay (ODMR)",
	369: "Rpc2portmap", // RENAME
	370: "codaauth2 - Coda authentication server",
	371: "ClearCase albd",
	383: "HP data alarm manager",
	384: "A Remote Network Server System",
	387: "AppleTalk Update-based Routing Protocol (AURP)",
	389: "Lightweight Directory Access Protocol (LDAP)",
	399: "Digital Equipment Corporation DECnet (Phase V+) over TCP/IP",
	401: "Uninterruptible power supply (UPS)",
	427: "Service Location Protocol (SLP)",
	433: "NNSP, part of Network News Transfer Protocol (NNTP)",
	434: "Mobile IP Agent",
	443: "Hypertext Transfer Protocol over TLS/SSL (HTTPS)",
	444: "Simple Network Paging Protocol (SNPP)",
	445: "Microsoft-DS (Directory Services) Active Directory",
	464: "Kerberos Change/Set password",
	465: "Authenticated SMTP over TLS/SSL (SMTPS)",
	475: "tcpnethaspsrv, Aladdin Knowledge Systems Hasp services",
	497: "Retrospect",
	500: "Internet Security Association and Key Management Protocol (ISAKMP) / Internet Key Exchange (IKE)",
}
